# Generated by Django 4.1.3 on 2022-11-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ak_img', models.FileField(default=None, max_length='250', null=True, upload_to='profile_img/')),
            ],
        ),
    ]
