# Generated by Django 4.1.3 on 2022-11-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desc',
            old_name='skill_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='desc',
            name='ak_img',
            field=models.FileField(default=None, null=True, upload_to='profile_img/'),
        ),
    ]
